#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
epm_io.py -- shared SBE ground-state file writers for the Python EPM references.

The files written here are byte-compatible with the reader in
src/ssbe/gs_info_ssbe.f90 (read_k_data / read_eigen_data / read_tm_data), exactly
like epm_gaas_reference.py's own writer. The GaAs reference keeps its private,
byte-validated copy; the CdS and graphene references use THIS module so the
file-format contract lives in one place.

Conventions (must match gs_info_ssbe and the GaAs reference):
  * k.data carries REDUCED (dimensionless) k-coordinates kx/b11 etc.; the SBE
    rebuilds Cartesian k via the b_matrix it derives from &system al. The cell
    must therefore be ORTHOGONAL (diagonal b_matrix) -- true for the GaAs cubic,
    CdS orthorhombic and graphene rectangular supercells.
  * eigen.data energies are in Hartree; occupations are 2 per filled band
    (spinless/scalar: nocc = nelec/2).
  * tm.data block 1 = p_tm = <u_m|p|u_n> (momentum, atomic units); block 2 =
    rvnl_tm = -i[r,Vnl], identically ZERO for a local pseudopotential.
All physical inputs must already be in atomic units (Hartree, Bohr^-1).
"""
import numpy as np


def monkhorst_pack(b_matrix, num_kgrid):
    """Uniform Monkhorst-Pack grid (equal weights), same ordering/formula as the
    GaAs reference and src/epm. b_matrix rows are b1,b2,b3 [a.u.]."""
    n1, n2, n3 = num_kgrid
    nk = n1 * n2 * n3
    kpoint = np.zeros((nk, 3))
    kweight = np.full(nk, 1.0 / nk)
    ik = 0
    for i1 in range(1, n1 + 1):
        for i2 in range(1, n2 + 1):
            for i3 in range(1, n3 + 1):
                f1 = (2 * i1 - n1 - 1) / (2.0 * n1)
                f2 = (2 * i2 - n2 - 1) / (2.0 * n2)
                f3 = (2 * i3 - n3 - 1) / (2.0 * n3)
                kpoint[ik] = f1 * b_matrix[0] + f2 * b_matrix[1] + f3 * b_matrix[2]
                ik += 1
    return kpoint, kweight


def momentum_matrix(kvec, Gcart, evec):
    """Local momentum p_mn = <m|(k+G)|n> in the band basis (p diagonal in the
    plane-wave basis). kvec, Gcart in a.u. (Bohr^-1); evec columns = eigenvectors."""
    nb = evec.shape[1]
    kpg = kvec[None, :] + Gcart
    p_mn = np.zeros((nb, nb, 3), dtype=complex)
    for idir in range(3):
        p_mn[:, :, idir] = evec.conj().T @ (kpg[:, idir][:, None] * evec)
    return p_mn


def write_epm_gs_files(sysname, outdir, material, kpoint_cart, b_matrix,
                       kweight, eigen, occup, p_tm, rvnl_tm, extra_note=''):
    """Write SYSNAME_k.data / _eigen.data / _tm.data (Hartree / a.u. / reduced k).

    kpoint_cart : (nk,3) Cartesian k [a.u.]      eigen : (nb,nk) [Ha]
    b_matrix    : rows b1,b2,b3 [a.u.] (diagonal) occup : (nb,nk)
    p_tm, rvnl_tm : (nb,nb,3,nk) complex [a.u.]
    """
    nk = kpoint_cart.shape[0]
    nb = eigen.shape[0]
    # reduced coordinates require an ORTHOGONAL cell (diagonal b_matrix)
    offdiag = np.abs(b_matrix - np.diag(np.diag(b_matrix))).max()
    if offdiag > 1e-8 * max(1.0, np.abs(b_matrix).max()):
        raise ValueError('write_epm_gs_files: cell is not orthogonal (b_matrix '
                         'not diagonal); reduced-coordinate k.data is undefined')
    b_diag = np.array([b_matrix[0, 0], b_matrix[1, 1], b_matrix[2, 2]])
    kred = kpoint_cart / b_diag

    note = f' -- {extra_note}' if extra_note else ''
    with open(f'{outdir}{sysname}_k.data', 'w') as f:
        f.write('# k-point data\n')
        f.write(f'# generated by EPM Python reference ({material}){note}\n')
        f.write(f'# material = {material}, nk = {nk}\n')
        f.write('# units: kx,ky,kz [reduced, dimensionless], weight (sums to 1)\n')
        f.write('# ik, kx, ky, kz, weight\n')
        for ik in range(nk):
            f.write('{:6d}{:18.10E}{:18.10E}{:18.10E}{:18.10E}\n'.format(
                ik + 1, kred[ik, 0], kred[ik, 1], kred[ik, 2], kweight[ik]))

    with open(f'{outdir}{sysname}_eigen.data', 'w') as f:
        f.write('# eigenvalue data\n')
        f.write(f'# generated by EPM Python reference ({material}){note}\n')
        f.write(f'# nk = {nk:6d}, nb = {nb:6d}\n')
        for ik in range(nk):
            f.write(f'# ik = {ik + 1:6d}\n')
            for ib in range(nb):
                f.write('{:6d}{:18.10E}{:18.10E}\n'.format(
                    ib + 1, eigen[ib, ik], occup[ib, ik]))

    with open(f'{outdir}{sysname}_tm.data', 'w') as f:
        f.write('# transition matrix data\n')
        f.write(f'# generated by EPM Python reference ({material}){note}\n')
        f.write('# block 1: p_tm = <u_m|p|u_n>  (ik, ib, jb, Re px, Im px, Re py, Im py, Re pz, Im pz)\n')
        _write_tm_block(f, p_tm, nk, nb)
        f.write('# block 2: rvnl_tm = -i[r,Vnl]  (all zero: local pseudopotential)\n')
        _write_tm_block(f, rvnl_tm, nk, nb)

    print(f'# EPM ({material}): wrote SBE ground-state files for sysname = {sysname} '
          f'(nk={nk}, nb={nb})')


def build_path(hs_points, labels, ndiv, b_matrix):
    """Sample a high-symmetry path. hs_points: {label: reduced-coord tuple};
    labels: ordered node labels; b_matrix rows = reciprocal vectors [a.u.] (the
    same dimension as the reduced coords, 2 or 3). Returns
    (qreds[N,d], kcarts[N,d], dists[N], node_dists[len(labels)])."""
    b = np.asarray(b_matrix)
    qreds, kcarts, dists, node_d = [], [], [], [0.0]
    cum = 0.0
    nseg = len(labels) - 1
    for iseg in range(nseg):
        qa = np.array(hs_points[labels[iseg]], dtype=float)
        qb = np.array(hs_points[labels[iseg + 1]], dtype=float)
        ka, kb = qa @ b, qb @ b
        seg_len = np.linalg.norm(kb - ka)
        last = (iseg == nseg - 1)
        for s in range(ndiv + (1 if last else 0)):
            t = s / ndiv
            q = qa + t * (qb - qa)
            qreds.append(q); kcarts.append(q @ b); dists.append(cum + t * seg_len)
        cum += seg_len
        node_d.append(cum)
    return np.array(qreds), np.array(kcarts), np.array(dists), node_d


def write_bandpath_file(sysname, outdir, material, labels, node_dists, dists,
                        qreds, eigen_ha, nv, spinor=0):
    """Write SYSNAME_bandpath.data (primitive-cell unfolded bands) in the exact
    format plot_sbe_results.py::_load_bandpath reads. eigen_ha: (N, nb) [Ha];
    qreds: (N, d) reduced coords (d=2 padded to 3)."""
    N, nb = eigen_ha.shape
    q3 = np.zeros((N, 3))
    q3[:, :qreds.shape[1]] = qreds
    fname = f'{outdir}{sysname}_bandpath.data'
    with open(fname, 'w') as f:
        f.write(f'# unfolded primitive-cell band path -- EPM {material} reference\n')
        f.write(f'# spinor = {spinor}\n')
        f.write(f'# nv = {nv}\n')
        f.write(f'# nb = {nb}\n')
        f.write('# nodes: ' + '  '.join(f'{l} {d:.7f}'
                                        for l, d in zip(labels, node_dists)) + '\n')
        f.write('# ik, dist, q1, q2, q3 (primitive reduced), E_1..E_nb [Ha]\n')
        for ik in range(N):
            f.write('{:6d}{:14.7f}{:10.5f}{:10.5f}{:10.5f}'.format(
                ik + 1, dists[ik], q3[ik, 0], q3[ik, 1], q3[ik, 2]))
            f.write(''.join(f'{x:18.10E}' for x in eigen_ha[ik]) + '\n')
    print(f'# EPM ({material}): wrote band path {fname} ({N} k-points, {nb} bands, nv={nv})')


def compute_unfold_map(build_H, kpoints, Gcart, hkls, coset, n_coset, nstate):
    """Compute the supercell-band -> coset unfold map (generic, any folding).

    build_H(k) -> H (npw x npw, Hermitian; units irrelevant -- only the spectral
    ORDER is used);  Gcart (npw,d);  hkls (npw,d) integer reciprocal indices;
    coset (npw,) in 0..n_coset-1 (which folding coset each plane wave belongs to).

    Returns (offsets[n_coset,3] int, isub[nstate,nk], ibprim[nstate,nk],
    wsub[n_coset,nstate,nk]):
      * offsets: the smallest-|G| representative of each coset, in integer
        supercell-reduced coords (padded to 3 components) -> the G0(s) the SBE
        uses as k_prim = k_sc + G0(s).
      * isub: dominant coset of each supercell band (1..n_coset).
      * ibprim: its primitive-band rank = position in the dominant coset block's
        spectrum (symmetric at degeneracies).
      * wsub: spectral weight of each band on each coset (sum_s = 1).
    Because the supercell H is block-diagonal over the cosets (exact folding),
    each band lives wholly in one coset; the weights make degeneracies symmetric.
    """
    npw = Gcart.shape[0]
    nk = len(kpoints)
    g2 = np.einsum('ij,ij->i', Gcart, Gcart)
    block_idx = [np.where(coset == s)[0] for s in range(n_coset)]
    offsets = np.zeros((n_coset, 3), dtype=int)
    for s in range(n_coset):
        idx = block_idx[s]
        rep = idx[np.argmin(g2[idx])]
        offsets[s, :hkls.shape[1]] = np.round(hkls[rep]).astype(int)

    isub = np.zeros((nstate, nk), dtype=int)
    ibprim = np.zeros((nstate, nk), dtype=int)
    wsub = np.zeros((n_coset, nstate, nk))
    for ik in range(nk):
        H = build_H(kpoints[ik])
        evals, evecs = np.linalg.eigh(H)
        w2 = np.abs(evecs[:, :nstate]) ** 2                  # (npw, nstate)
        ws = np.array([w2[block_idx[s]].sum(axis=0) for s in range(n_coset)])
        ws /= np.maximum(ws.sum(axis=0), 1e-300)
        dom = np.argmax(ws, axis=0)                          # (nstate,)
        block_evals = [np.sort(np.linalg.eigvalsh(H[np.ix_(bi, bi)]))
                       for bi in block_idx]
        for ib in range(nstate):
            s = dom[ib]
            isub[ib, ik] = s + 1
            ibprim[ib, ik] = 1 + int(np.searchsorted(block_evals[s], evals[ib] - 1e-9))
            wsub[:, ib, ik] = ws[:, ib]
    return offsets, isub, ibprim, wsub


def write_unfold_file(sysname, outdir, material, n_coset, nv_prim,
                      offsets, isub, ibprim, wsub):
    """Write SYSNAME_unfold.data (N-coset format read by gs_info_ssbe). The
    header carries n_coset (4 = cubic FCC, 2 = wurtzite/rectangular 2-fold)."""
    nstate, nk = isub.shape
    fname = f'{outdir}{sysname}_unfold.data'
    with open(fname, 'w') as f:
        f.write('# unfold map (supercell band -> coset spectral weights)\n')
        f.write('# nk, nb, nv_prim, n_coset\n')
        f.write(f'{nk:8d}{nstate:8d}{nv_prim:8d}{n_coset:8d}\n')
        f.write('# isub, offset G0 (sc reduced)\n')
        for s in range(n_coset):
            f.write(f'{s + 1:4d}{offsets[s, 0]:4d}{offsets[s, 1]:4d}{offsets[s, 2]:4d}\n')
        f.write('# ik, ib, isub, ibprim, w1..w_ncoset\n')
        for ik in range(nk):
            for ib in range(nstate):
                f.write('{:6d}{:6d}{:4d}{:6d}'.format(
                    ik + 1, ib + 1, isub[ib, ik], ibprim[ib, ik]))
                f.write(''.join(f'{wsub[s, ib, ik]:12.6f}' for s in range(n_coset)) + '\n')
    print(f'# EPM ({material}): wrote unfold map {fname} '
          f'(nk={nk}, nb={nstate}, n_coset={n_coset}, nv_prim={nv_prim})')


def _write_tm_block(f, mat, nk, nb):
    for ik in range(nk):
        for ib in range(nb):
            for jb in range(nb):
                px, py, pz = mat[ib, jb, 0, ik], mat[ib, jb, 1, ik], mat[ib, jb, 2, ik]
                f.write('{:6d}{:6d}{:6d}{:18.10E}{:18.10E}{:18.10E}{:18.10E}{:18.10E}{:18.10E}\n'.format(
                    ik + 1, ib + 1, jb + 1,
                    px.real, px.imag, py.real, py.imag, pz.real, pz.imag))
