"""
GaAs PRIMITIVE-CELL EPM ground state -- 2-atom FCC, NON-orthogonal, NO folding.

This is the "new output type without folding" companion to epm_gaas_reference.py
(the cubic 8-atom supercell). It produces the clean primitive zincblende bands
on the FCC (triclinic, non-orthogonal) Brillouin zone so the SBE can be run on
the *unfolded* problem -- the decisive test of whether the folded multiband
manifold (dense inter-/intra-coset avoided crossings) was responsible for the
"L over-populates Gamma" pattern, or whether it is genuine primitive physics.

Geometry (non-orthogonal):
  real FCC primitive vectors  a1 = a/2 (0,1,1), a2 = a/2 (1,0,1), a3 = a/2 (1,1,0)
  reciprocal (BCC)            b_i = 2 pi (a_j x a_k)/V ;  V = a^3/4
The FCC reciprocal lattice is the set of cubic (2pi/a)(h,k,l) with h,k,l ALL EVEN
or ALL ODD -- exactly the coset-0 / same-parity plane waves. So the primitive
basis is the cubic plane-wave basis restricted to one parity class: no folding,
no cosets, no unfold map, no sublattice/HF projection. We reuse the cubic EPM's
Cohen-Bergstresser Hamiltonian and momentum machinery verbatim on this basis.

Output: SYSNAME_k.data (Cartesian k, uniform weights), _eigen.data, _tm.data
(no _unfold.data). 8 bands = 4 valence + 4 conduction; nelec = 8 (occ 2/band).
The k-grid is a Monkhorst-Pack mesh on the (non-orthogonal) BCC reciprocal
lattice -- a triclinic Cartesian grid; the SBE reads Cartesian k directly and
the equal MP weights are correct (each cell has equal volume V_BZ/Nk).
"""
import sys
import numpy as np

import epm_gaas_reference as ref   # reuse form factors, Hamiltonian, momentum
import epm_io

ANG_TO_BOHR = 1.0 / 0.52917721067
A_LATTICE_AU = 10.683            # a = 5.653 Angstrom (matches the cubic reference 10.68)
PW_CUTOFF_RY = 11.1              # |G|^2 cutoff in (2pi/a)^2 units (same as cubic)
MATERIAL = 'GaAs'
SYSNAME = 'GaAs_prim'
NUM_KGRID = (8, 8, 8)            # MP mesh on the FCC reciprocal lattice
NELEC = 8                        # 2 atoms (Ga 3 + As 5) -> 8 valence e- -> 4 filled bands
NSTATE = 8                       # 4 valence + 4 conduction
# Spin-orbit (spinor) mode. False = scalar (npw problem, NSTATE bands, occ 2);
# True = spinor (2*npw problem, 2*NSTATE spin-orbit-split bands, occ 1, with the
# nonlocal SO velocity correction in tm block 2). The SO machinery (kappa.sigma
# kernel, mu calibration to the Gamma8-Gamma7 splitting) is reused verbatim from
# epm_gaas_reference; on the single-parity primitive basis dG is always all-even,
# so the SO structure factor is fully active -- the genuine primitive SO problem.
INCLUDE_SPIN_ORBIT = False


def fcc_primitive_vectors_au(a):
    """Non-orthogonal FCC primitive real-space vectors [Bohr]."""
    return (np.array([0.0, 0.5, 0.5]) * a,
            np.array([0.5, 0.0, 0.5]) * a,
            np.array([0.5, 0.5, 0.0]) * a)


def reciprocal_vectors(a1, a2, a3):
    """General (non-orthogonal) reciprocal lattice: rows b1,b2,b3 [a.u.], + V."""
    V = np.dot(a1, np.cross(a2, a3))
    b1 = 2 * np.pi * np.cross(a2, a3) / V
    b2 = 2 * np.pi * np.cross(a3, a1) / V
    b3 = 2 * np.pi * np.cross(a1, a2) / V
    return np.array([b1, b2, b3]), V


def build_pw_basis_fcc(a, cutoff_ry):
    """FCC primitive plane waves = cubic (2pi/a)(h,k,l) with h,k,l ALL EVEN or
    ALL ODD (the BCC reciprocal lattice), |G|^2 <= cutoff in (2pi/a)^2 units."""
    twopi_a = 2.0 * np.pi / a
    nmax = int(np.ceil(np.sqrt(cutoff_ry))) + 1
    G, G2 = [], []
    for h in range(-nmax, nmax + 1):
        for k in range(-nmax, nmax + 1):
            for l in range(-nmax, nmax + 1):
                if not ((h % 2 == k % 2) and (k % 2 == l % 2)):
                    continue                       # keep only one parity class (coset 0)
                g2 = h * h + k * k + l * l
                if g2 <= cutoff_ry + 1e-8:
                    G.append(twopi_a * np.array([h, k, l], dtype=float))
                    G2.append(g2)
    return np.array(G), np.array(G2, dtype=int)


def _write_gs_files_nonorth(outdir, kfrac, kpoint_cart, kweight, eigen, occup,
                            p_tm, rvnl_tm, note, b_matrix=None):
    """Like epm_io.write_epm_gs_files but for a NON-orthogonal cell: k.data
    carries the well-defined Monkhorst-Pack FRACTIONAL coords (reduced, in
    [-0.5,0.5)); the SBE reads them only as a per-k label (clean dynamics uses
    the band eigen/p, not k). Cartesian k for analysis = kfrac @ b_matrix.
    The reciprocal vectors are written into the header (# b1/# b2/# b3 [a.u.])
    so the plotter can un-shear the triclinic grid into a Cartesian BZ heatmap."""
    nk = kpoint_cart.shape[0]
    nb = eigen.shape[0]
    with open(f'{outdir}{SYSNAME}_k.data', 'w') as f:
        f.write('# k-point data\n')
        f.write(f'# generated by EPM Python reference ({MATERIAL}) -- {note}\n')
        f.write(f'# material = {MATERIAL}, nk = {nk}\n')
        if b_matrix is not None:
            for i in range(3):
                f.write('# b{} = {:18.10E}{:18.10E}{:18.10E}  [a.u.]\n'.format(
                    i + 1, b_matrix[i, 0], b_matrix[i, 1], b_matrix[i, 2]))
        f.write('# units: kx,ky,kz [reduced fractional of the FCC reciprocal lattice], weight\n')
        f.write('# ik, kx, ky, kz, weight\n')
        for ik in range(nk):
            f.write('{:6d}{:18.10E}{:18.10E}{:18.10E}{:18.10E}\n'.format(
                ik + 1, kfrac[ik, 0], kfrac[ik, 1], kfrac[ik, 2], kweight[ik]))
    with open(f'{outdir}{SYSNAME}_eigen.data', 'w') as f:
        f.write('# eigenvalue data\n')
        f.write(f'# generated by EPM Python reference ({MATERIAL}) -- {note}\n')
        f.write(f'# nk = {nk:6d}, nb = {nb:6d}\n')
        for ik in range(nk):
            f.write(f'# ik = {ik + 1:6d}\n')
            for ib in range(nb):
                f.write('{:6d}{:18.10E}{:18.10E}\n'.format(ib + 1, eigen[ib, ik], occup[ib, ik]))
    with open(f'{outdir}{SYSNAME}_tm.data', 'w') as f:
        f.write('# transition matrix data\n')
        f.write(f'# generated by EPM Python reference ({MATERIAL}) -- {note}\n')
        f.write('# block 1: p_tm = <u_m|p|u_n>  (ik, ib, jb, Re px, Im px, Re py, Im py, Re pz, Im pz)\n')
        epm_io._write_tm_block(f, p_tm, nk, nb)
        f.write('# block 2: rvnl_tm = -i[r,Vnl]  (all zero: local pseudopotential)\n')
        epm_io._write_tm_block(f, rvnl_tm, nk, nb)


def main_gs(outdir='./'):
    a = A_LATTICE_AU
    a1, a2, a3 = fcc_primitive_vectors_au(a)
    b_matrix, V = reciprocal_vectors(a1, a2, a3)
    Gcart, G2 = build_pw_basis_fcc(a, PW_CUTOFF_RY)
    kpoint, kweight = epm_io.monkhorst_pack(b_matrix, NUM_KGRID)
    kfrac = kpoint @ np.linalg.inv(b_matrix)        # Cartesian -> fractional (reduced)
    nk = len(kpoint)
    npw = len(Gcart)
    spinor = INCLUDE_SPIN_ORBIT
    if spinor:
        nb, nocc, occ_val = 2 * NSTATE, NELEC, 1.0
    else:
        nb, nocc, occ_val = NSTATE, NELEC // 2, 2.0
    print(f'# EPM {MATERIAL} PRIMITIVE FCC (2-atom, non-orthogonal, NO folding)')
    print(f'#   a = {a} Bohr,  V_cell = {V:.3f} Bohr^3 (= a^3/4 = {a**3/4:.3f})')
    print(f'#   plane waves = {npw} (all-same-parity){" -> spinor dim "+str(2*npw) if spinor else ""}'
          f', k-points = {nk}, bands = {nb}')
    print(f'#   spin-orbit (spinor) = {spinor}; valence e- = {NELEC} '
          f'(occ {occ_val:g}/band -> {nocc} filled)')

    mu = 0.0
    if spinor:
        # Calibrate mu to Delta0 (Gamma8-Gamma7) on the PRIMITIVE basis. The ref
        # calibrator indexes the valence manifold by its NELEC, so point it at the
        # primitive electron count for the duration of the calibration.
        ref.MATERIAL, ref_nelec_saved = MATERIAL, ref.NELEC
        ref.NELEC = NELEC
        mu = ref.calibrate_so_mu(Gcart, a)
        ref.NELEC = ref_nelec_saved

    eigen = np.zeros((nb, nk))
    occup = np.zeros((nb, nk))
    p_tm = np.zeros((nb, nb, 3, nk), dtype=complex)
    rvnl_tm = np.zeros((nb, nb, 3, nk), dtype=complex)   # scalar: 0; spinor: SO velocity
    for ik in range(nk):
        if spinor:
            H, v_so = ref.build_hamiltonian_spinor(MATERIAL, kpoint[ik], Gcart, a,
                                                   mu, with_velocity=True)
            ev, evec = np.linalg.eigh(H)
            evec_nb = evec[:, :nb]
            p_tm[:, :, :, ik] = ref.momentum_matrix_spinor(kpoint[ik], Gcart, evec_nb)
            for idir in range(3):
                rvnl_tm[:, :, idir, ik] = evec_nb.conj().T @ (v_so[idir] @ evec_nb)
        else:
            H = ref.build_hamiltonian_sc(MATERIAL, kpoint[ik], Gcart, a)
            ev, evec = np.linalg.eigh(H)
            p_tm[:, :, :, ik] = ref.momentum_matrix(kpoint[ik], Gcart, evec[:, :nb])
        eigen[:, ik] = ev[:nb]
        occup[:nocc, ik] = occ_val
        if (ik + 1) % 64 == 0:
            print(f'#   ... diagonalized k-point {ik+1}/{nk}')

    note = ('PRIMITIVE FCC (2-atom, non-orthogonal, unfolded -- no cosets'
            + (', spin-orbit' if spinor else '') + ')')
    _write_gs_files_nonorth(
        outdir, kfrac, kpoint, kweight, eigen, occup, p_tm, rvnl_tm,
        note=note, b_matrix=b_matrix)
    # Cartesian k saved separately for the valley analysis (k_cart = kfrac @ b_matrix).
    np.savez(f'{outdir}{SYSNAME}_kcart.npz', kcart=kpoint, b_matrix=b_matrix,
             a=A_LATTICE_AU)
    print(f'# EPM ({MATERIAL} primitive): wrote {SYSNAME}_k/_eigen/_tm.data (nk={nk}, nb={nb})')


# FCC Brillouin-zone high-symmetry points, Cartesian in units of (2pi/a)
FCC_HS = {'L': (0.5, 0.5, 0.5), 'Gamma': (0.0, 0.0, 0.0),
          'X': (1.0, 0.0, 0.0), 'W': (1.0, 0.5, 0.0), 'K': (0.75, 0.75, 0.0)}
FCC_PATH = ['L', 'Gamma', 'X', 'W', 'K', 'Gamma']


def main_bandpath(outdir='./', ndiv=60):
    """Emit SYSNAME_bandpath.data: the clean PRIMITIVE bands along the FCC path
    L-Gamma-X-W-K-Gamma. Cartesian path length (correct for the non-orthogonal
    cell). Read directly by plot_sbe_results.py."""
    a = A_LATTICE_AU
    twopi_a = 2.0 * np.pi / a
    b_matrix, _ = reciprocal_vectors(*fcc_primitive_vectors_au(a))
    binv = np.linalg.inv(b_matrix)
    Gcart, _ = build_pw_basis_fcc(a, PW_CUTOFF_RY)
    spinor = INCLUDE_SPIN_ORBIT
    nb = 2 * NSTATE if spinor else NSTATE
    nv = NELEC if spinor else NELEC // 2
    mu = 0.0
    if spinor:
        ref.MATERIAL, saved = MATERIAL, ref.NELEC
        ref.NELEC = NELEC
        mu = ref.calibrate_so_mu(Gcart, a)
        ref.NELEC = saved
    qreds, dists, node_d, eig = [], [], [0.0], []
    cum = 0.0
    nodes = FCC_PATH
    for iseg in range(len(nodes) - 1):
        ca = twopi_a * np.array(FCC_HS[nodes[iseg]])
        cb = twopi_a * np.array(FCC_HS[nodes[iseg + 1]])
        seg = np.linalg.norm(cb - ca)
        last = (iseg == len(nodes) - 2)
        for s in range(ndiv + (1 if last else 0)):
            t = s / ndiv
            kc = ca + t * (cb - ca)
            if spinor:
                ev = np.linalg.eigvalsh(ref.build_hamiltonian_spinor(MATERIAL, kc, Gcart, a, mu))
            else:
                ev = np.linalg.eigvalsh(ref.build_hamiltonian_sc(MATERIAL, kc, Gcart, a))
            eig.append(ev[:nb]); qreds.append(kc @ binv)
            dists.append(cum + t * seg)
        cum += seg
        node_d.append(cum)
    epm_io.write_bandpath_file(SYSNAME, outdir, MATERIAL, nodes, node_d,
                               np.array(dists), np.array(qreds), np.array(eig), nv,
                               spinor=1 if spinor else 0)


def report_gap():
    """Print the Gamma/X/L vertical gaps (validation). With spin-orbit on, the
    valence top is the Gamma8 manifold and the gap is measured to it."""
    a = A_LATTICE_AU
    Gcart, _ = build_pw_basis_fcc(a, PW_CUTOFF_RY)
    twopi_a = 2.0 * np.pi / a
    HA = 27.211386245988
    spinor = INCLUDE_SPIN_ORBIT
    nocc = NELEC if spinor else NELEC // 2     # filled bands (occ 1 spinor / 2 scalar)
    mu = 0.0
    if spinor:
        ref.MATERIAL, saved = MATERIAL, ref.NELEC
        ref.NELEC = NELEC
        mu = ref.calibrate_so_mu(Gcart, a)
        ref.NELEC = saved
    pts = {'Gamma': np.zeros(3),
           'X': twopi_a * np.array([1.0, 0.0, 0.0]),
           'L': twopi_a * np.array([0.5, 0.5, 0.5])}
    for name, kv in pts.items():
        if spinor:
            ev = np.linalg.eigvalsh(ref.build_hamiltonian_spinor(MATERIAL, kv, Gcart, a, mu))
        else:
            ev = np.linalg.eigvalsh(ref.build_hamiltonian_sc(MATERIAL, kv, Gcart, a))
        gap = (ev[nocc] - ev[nocc - 1]) * HA
        print(f'  {name:6s}: E_v={ev[nocc-1]*HA:7.3f}  E_c={ev[nocc]*HA:7.3f}  vertical gap = {gap:6.3f} eV')


if __name__ == '__main__':
    mode = sys.argv[1] if len(sys.argv) > 1 else ''
    if mode == 'gap':
        report_gap()
    elif mode == 'bandpath':
        main_bandpath()
    elif mode == 'gs':
        main_gs()
        main_bandpath()
    else:
        report_gap()
        print()
        main_gs()
        main_bandpath()
