#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
epm_io.py -- shared SBE ground-state file writers for the Python EPM references.

The files written here are byte-compatible with the reader in
src/ssbe/gs_info_ssbe.f90 (read_k_data / read_eigen_data / read_tm_data), exactly
like epm_gaas_reference.py's own writer. The GaAs reference keeps its private,
byte-validated copy; the CdS and graphene references use THIS module so the
file-format contract lives in one place.

Conventions (must match gs_info_ssbe and the GaAs reference):
  * k.data carries REDUCED (dimensionless) k-coordinates kx/b11 etc.; the SBE
    rebuilds Cartesian k via the b_matrix it derives from &system al. The cell
    must therefore be ORTHOGONAL (diagonal b_matrix) -- true for the GaAs cubic,
    CdS orthorhombic and graphene rectangular supercells.
  * eigen.data energies are in Hartree; occupations are 2 per filled band
    (spinless/scalar: nocc = nelec/2).
  * tm.data block 1 = p_tm = <u_m|p|u_n> (momentum, atomic units); block 2 =
    rvnl_tm = -i[r,Vnl], identically ZERO for a local pseudopotential.
All physical inputs must already be in atomic units (Hartree, Bohr^-1).
"""
import numpy as np


def monkhorst_pack(b_matrix, num_kgrid):
    """Uniform Monkhorst-Pack grid (equal weights), same ordering/formula as the
    GaAs reference and src/epm. b_matrix rows are b1,b2,b3 [a.u.]."""
    n1, n2, n3 = num_kgrid
    nk = n1 * n2 * n3
    kpoint = np.zeros((nk, 3))
    kweight = np.full(nk, 1.0 / nk)
    ik = 0
    for i1 in range(1, n1 + 1):
        for i2 in range(1, n2 + 1):
            for i3 in range(1, n3 + 1):
                f1 = (2 * i1 - n1 - 1) / (2.0 * n1)
                f2 = (2 * i2 - n2 - 1) / (2.0 * n2)
                f3 = (2 * i3 - n3 - 1) / (2.0 * n3)
                kpoint[ik] = f1 * b_matrix[0] + f2 * b_matrix[1] + f3 * b_matrix[2]
                ik += 1
    return kpoint, kweight


def momentum_matrix(kvec, Gcart, evec):
    """Local momentum p_mn = <m|(k+G)|n> in the band basis (p diagonal in the
    plane-wave basis). kvec, Gcart in a.u. (Bohr^-1); evec columns = eigenvectors."""
    nb = evec.shape[1]
    kpg = kvec[None, :] + Gcart
    p_mn = np.zeros((nb, nb, 3), dtype=complex)
    for idir in range(3):
        p_mn[:, :, idir] = evec.conj().T @ (kpg[:, idir][:, None] * evec)
    return p_mn


def write_epm_gs_files(sysname, outdir, material, kpoint_cart, b_matrix,
                       kweight, eigen, occup, p_tm, rvnl_tm, extra_note=''):
    """Write SYSNAME_k.data / _eigen.data / _tm.data (Hartree / a.u. / reduced k).

    kpoint_cart : (nk,3) Cartesian k [a.u.]      eigen : (nb,nk) [Ha]
    b_matrix    : rows b1,b2,b3 [a.u.] (diagonal) occup : (nb,nk)
    p_tm, rvnl_tm : (nb,nb,3,nk) complex [a.u.]
    """
    nk = kpoint_cart.shape[0]
    nb = eigen.shape[0]
    # reduced coordinates require an ORTHOGONAL cell (diagonal b_matrix)
    offdiag = np.abs(b_matrix - np.diag(np.diag(b_matrix))).max()
    if offdiag > 1e-8 * max(1.0, np.abs(b_matrix).max()):
        raise ValueError('write_epm_gs_files: cell is not orthogonal (b_matrix '
                         'not diagonal); reduced-coordinate k.data is undefined')
    b_diag = np.array([b_matrix[0, 0], b_matrix[1, 1], b_matrix[2, 2]])
    kred = kpoint_cart / b_diag

    note = f' -- {extra_note}' if extra_note else ''
    with open(f'{outdir}{sysname}_k.data', 'w') as f:
        f.write('# k-point data\n')
        f.write(f'# generated by EPM Python reference ({material}){note}\n')
        f.write(f'# material = {material}, nk = {nk}\n')
        f.write('# units: kx,ky,kz [reduced, dimensionless], weight (sums to 1)\n')
        f.write('# ik, kx, ky, kz, weight\n')
        for ik in range(nk):
            f.write('{:6d}{:18.10E}{:18.10E}{:18.10E}{:18.10E}\n'.format(
                ik + 1, kred[ik, 0], kred[ik, 1], kred[ik, 2], kweight[ik]))

    with open(f'{outdir}{sysname}_eigen.data', 'w') as f:
        f.write('# eigenvalue data\n')
        f.write(f'# generated by EPM Python reference ({material}){note}\n')
        f.write(f'# nk = {nk:6d}, nb = {nb:6d}\n')
        for ik in range(nk):
            f.write(f'# ik = {ik + 1:6d}\n')
            for ib in range(nb):
                f.write('{:6d}{:18.10E}{:18.10E}\n'.format(
                    ib + 1, eigen[ib, ik], occup[ib, ik]))

    with open(f'{outdir}{sysname}_tm.data', 'w') as f:
        f.write('# transition matrix data\n')
        f.write(f'# generated by EPM Python reference ({material}){note}\n')
        f.write('# block 1: p_tm = <u_m|p|u_n>  (ik, ib, jb, Re px, Im px, Re py, Im py, Re pz, Im pz)\n')
        _write_tm_block(f, p_tm, nk, nb)
        f.write('# block 2: rvnl_tm = -i[r,Vnl]  (all zero: local pseudopotential)\n')
        _write_tm_block(f, rvnl_tm, nk, nb)

    print(f'# EPM ({material}): wrote SBE ground-state files for sysname = {sysname} '
          f'(nk={nk}, nb={nb})')


def _write_tm_block(f, mat, nk, nb):
    for ik in range(nk):
        for ib in range(nb):
            for jb in range(nb):
                px, py, pz = mat[ib, jb, 0, ik], mat[ib, jb, 1, ik], mat[ib, jb, 2, ik]
                f.write('{:6d}{:6d}{:6d}{:18.10E}{:18.10E}{:18.10E}{:18.10E}{:18.10E}{:18.10E}\n'.format(
                    ik + 1, ib + 1, jb + 1,
                    px.real, px.imag, py.real, py.imag, pz.real, pz.imag))
